Repository Nononolan45/back_hackathlon, pull requests merged in 2020-11, with the labels that each got.

#14 login creation
  api/controllers/userController.js
  api/providers/bcrypt.js
  api/routes/userRoute.js
Labels: enhancement

#16 Feature/middleware
  api/index.js
  api/middleware/jwtMiddleware.js
  api/middleware/projectMiddleware.js
  api/models/projectModel.js
  api/models/userModel.js
  api/routes/memberRoute.js
  api/routes/projectRoute.js
Labels: enhancement

#18 add set data to school and user
  data/import.sh
  data/schools.json
  data/users.json
  docker-compose.yml
Labels: enhancement

#20 Geature/swagger update
  api/controllers/projectController.js
  api/index.js
  api/middleware/jwtMiddleware.js
  api/middleware/projectMiddleware.js
  api/routes/projectRoute.js
  api/swagger/swagger.json
  api/yarn.lock
Labels: documentation

#23 add .env.example
  .env.example
  api/controllers/userController.js
  api/index.js
  api/middleware/jwtMiddleware.js
  api/yarn.lock
Labels: documentation, enhancement

#24 Feature/readme
  README.md
  docker-compose.yml
Labels: documentation, enhancement
